/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stonectr_serial_SerialController */

#ifndef _Included_stonectr_serial_SerialController
#define _Included_stonectr_serial_SerialController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stonectr_serial_SerialController
 * Method:    init_
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_init_1
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_release
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    openScanPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_openScanPort
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    closeScanPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_closeScanPort
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    openWakePort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_openWakePort
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    closeWakePort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_closeWakePort
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    openROSPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_openROSPort
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    closeROSPort
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_closeROSPort
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    startWakeRcv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_startWakeRcv
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    stopWakeRcv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_stopWakeRcv
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    startScanRcv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_startScanRcv
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    stopScanRcv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_stopScanRcv
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    startRosRcv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_startRosRcv
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    stopRosRcv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_stopRosRcv
  (JNIEnv *, jclass);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendForward__
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendBackward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendBackward__
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendLeft__
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendRight__
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendStop
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendForward
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendForward__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendBackward
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendBackward__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendLeft
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendLeft__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendRight
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendRight__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    platformUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_platformUp
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    platformDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_platformDown
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    platformStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_platformStop
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    platformBottom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_platformBottom
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    moveTo
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_moveTo
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    gotoScan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_gotoScan
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    patrol
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_patrol
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    navigation
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_navigation
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendMoveToLiving
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendMoveToLiving
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendMoveToBedroom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendMoveToBedroom
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendMoveToYard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendMoveToYard
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    sendPatrol
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_sendPatrol
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    voiceprintCheck
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_voiceprintCheck
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    voiceCheckSuccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_voiceCheckSuccess
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    voiceCheckFail
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_voiceCheckFail
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    voiceChec2kFail
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_voiceChec2kFail
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    init
 * Signature: (Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_stonectr_serial_SerialController_open
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stonectr_serial_SerialController_close
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    read
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_stonectr_serial_SerialController_read
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_stonectr_serial_SerialController_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    isOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_stonectr_serial_SerialController_isOpen
  (JNIEnv *, jobject);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_stonectr_serial_SerialController_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     stonectr_serial_SerialController
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_stonectr_serial_SerialController_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
